sudo: required

services:
  - docker

env:
  matrix:
    - ANDROID_VERSION=29
    - ANDROID_VERSION=28
    - ANDROID_VERSION=27
    - ANDROID_VERSION=26
    - ANDROID_VERSION=25

script:
  - make "android$ANDROID_VERSION"
  - chmod --recursive a+wrx .
  - >
    docker run
    -it
    --volume
    $(pwd):/home/dev/android_project:rw
    --user dev
    "android-container:$ANDROID_VERSION"
    bash ./tests/run_smoke_tests.sh
    /home/dev/android_project/tests/JavaTestApplication
  - >
    docker run
    -it
    --volume
    $(pwd):/home/dev/android_project:rw
    --user dev
    "android-container:$ANDROID_VERSION"
    bash ./tests/run_smoke_tests.sh
    /home/dev/android_project/tests/KotlinTestApplication
